language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

before_install:
  # Strangely enough numpy is already installed on Travis's VMs
  - pip uninstall -y numpy
  - pip install -r requirements_dev.txt

install:
  - pip install -e .

script:
  - pytest -xvv tests
  - safety check
