os: linux

dist: focal

language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - pip install -r requirements_dev.txt

install:
  - pip install -e .

script:
  - pytest -xvv tests
  - safety check
